# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36a64902b10874886eb3c21608889e0936e9409ddfa2b27941db4acd2604227c6886a5e025bbb0a19d4ebef60e8a3c4c668670ea1814932d1d7fd885b30980d5

test:
  secret_key_base: 1728f9f43c6d532dc17c4cfd7a44fba000918d5421938c69ebe134c5122b57308489cb72a6f138e5450f7aabd148c19f73c4056d28f4d94d10acaec2bf825653

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
